### ISSUE TITLE
Add custom recipes

### ISSUE THREAD

**Issue by IrusVirus** [bsergent/RealMail#16]
Hi ha1fBit, is it possible to add changeable recipes for the mailbox and the stationery?
So I can add for payment reasons a goldnugget ore something... thx :)

**Comment by bsergent** [comment]
Yes it is, I just programmed something similar for another plugin I was working on and could practically just copy and paste, so it'll be in the next version. Also, if you're doing payment stuff, would you like Vault compatibility for fees and such for sending mail and packaging?

**Comment by IrusVirus** [comment]
Our iconomy system is based on 'goldnuggets' and no "virtual money" ^^

We would be happy about this change :) when would it released?

**Comment by bsergent** [comment]
Ah okay, so I'll put the virtual money support on the back-burner for a bit. 

In terms of a release date, I could go ahead and get you a development build with the golden nuggets hardcoded into the recipes by Friday. For the official release, I've still got a few items on my update list I need to finish, plus I've been redoing my servers too so that's been taking up a lot of time.

**Comment by IrusVirus** [comment]
Ok, that will be great! :)
Please add both recipes +1 goldnugget ^^

**Comment by bsergent** [comment]
Here's the temporary build for you: https://dl.dropboxusercontent.com/u/7798886/RealMail-v0.3.2.16.zip. I added a gold nugget to both recipes as you specified. :)

**Comment by IrusVirus** [comment]
It works, thx :)

We use the Plugin RecipeManager2 (http://dev.bukkit.org/bukkit-plugins/recipemanager) for our custom recipes... now when someone will craft another thing comes following error:

[11:48:27 ERROR]: Could not pass event CraftItemEvent to RealMail v0.3.2.16
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot18-ADRUNDAAL.jar:git-Spigot-c3c767f-33d5de3]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot18-ADRUNDAAL.jar:git-Spigot-c3c767f-33d5de3]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot18-ADRUNDAAL.jar:git-Spigot-c3c767f-33d5de3]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot18-ADRUNDAAL.jar:git-Spigot-c3c767f-33d5de3]
        at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:1588) [spigot18-ADRUNDAAL.jar:git-Spigot-c3c767f-33d5de3]
        at net.minecraft.server.v1_8_R1.PacketPlayInWindowClick.a(SourceFile:31) [spigot18-ADRUNDAAL.jar:git-Spigot-c3c767f-33d5de3]
        at net.minecraft.server.v1_8_R1.PacketPlayInWindowClick.a(SourceFile:9) [spigot18-ADRUNDAAL.jar:git-Spigot-c3c767f-33d5de3]
        at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [spigot18-ADRUNDAAL.jar:git-Spigot-c3c767f-33d5de3]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_45-internal]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_45-internal]
        at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:696) [spigot18-ADRUNDAAL.jar:git-Spigot-c3c767f-33d5de3]
        at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot18-ADRUNDAAL.jar:git-Spigot-c3c767f-33d5de3]
        at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634) [spigot18-ADRUNDAAL.jar:git-Spigot-c3c767f-33d5de3]
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537) [spigot18-ADRUNDAAL.jar:git-Spigot-c3c767f-33d5de3]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45-internal]
Caused by: java.lang.NullPointerException
        at com.challengercity.plugins.realmail.RealMail$MailListener.onCraft(RealMail.java:987) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45-internal]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_45-internal]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_45-internal]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_45-internal]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[spigot18-ADRUNDAAL.jar:git-Spigot-c3c767f-33d5de3]
        ... 14 more

But the recipes works(!)... only the error is not pretty ^^

**Comment by bsergent** [comment]
Hmm, it seems that RealMail doesn't play well with any custom crafting plugins. Issue #17  is just for that now.

**Comment by IrusVirus** [comment]
When a player have the permission 'realmail.user.craft.stationary' then he can build a mailbox without the permission 'realmail.user.craft.mailbox'... can you check this pls? ('-realmail.user.*' is global added [PermissionsEx])

**Comment by manuelgu** [comment]
> When a player have the permission 'realmail.user.craft.stationary' then he can build a mailbox without the permission 'realmail.user.craft.mailbox'... can you check this pls? ('-realmail.user.*' is global added [PermissionsEx])

This may fix it https://github.com/bsergent/RealMail/pull/18

**Comment by IrusVirus** [comment]
Thx manuelgu, now I need a downloadlink ... ^^

**Comment by bsergent** [comment]
Here's a [download link [v0.3.2d16.2]](https://dl.dropboxusercontent.com/u/7798886/RealMail-v0.3.2d16.2.zip) for the permission fixes.

**Comment by manuelgu** [comment]
@bsergent v0.3.2d16.2 does not contain the custom recipe anymore. May I go ahead and build a custom version for them?

**Comment by bsergent** [comment]
Oops, ya that would be great if you could

**Comment by manuelgu** [comment]
@IrusVirus [RealMail Download containg Permission Fix & Gold Nugget Recipe](https://dl.dropbox.com/s/oymlkwwx0z8ncf3/RealMail.jar?dl=0)

**Comment by IrusVirus** [comment]
thx, it works =D
